/**
 * @file shoes.h
 * @brief C interface for the shoes proxy library (auto-generated by cbindgen).
 *
 * Provides C-compatible functions for embedding the shoes VPN/proxy engine
 * into iOS applications via Swift or Objective-C.
 */

#ifndef SHOES_H
#define SHOES_H

#include <stdbool.h>
#include <stdint.h>

/**
 * Socket protector callback type.
 * Called from Rust to protect sockets from VPN routing.
 * The callback receives a file descriptor and should return true if protected successfully.
 */
typedef bool (*ProtectSocketCallback)(int fd);

/**
 * Traffic statistics callback type.
 * Called about once a second with cumulative byte counts since `shoes_start`.
 *
 * * `upload_bytes` - total bytes sent from the device to the proxy.
 * * `download_bytes` - total bytes received from the proxy to the device.
 *
 * Invoked from a Rust worker thread, not the caller's thread.
 */
typedef void (*ShoesTrafficCallback)(uint64_t upload_bytes, uint64_t download_bytes);

/**
 * Initialize the shoes library.
 *
 * # Arguments
 * * `log_level` - Log level string: "error", "warn", "info", "debug", "trace"
 *
 * # Returns
 * * 0 on success
 * * -1 on error
 *
 * # Safety
 * `log_level` must be a valid null-terminated C string.
 */
int shoes_init(const char *log_level);

/**
 * Start the shoes VPN service.
 *
 * # Arguments
 * * `config_yaml` - YAML configuration string (must include device_fd in TUN config)
 * * `protect_callback` - Callback function to protect sockets from VPN routing
 * * `traffic_callback` - Callback invoked about once a second with cumulative
 *   upload and download byte counts
 *
 * # Returns
 * * Handle (> 0) on success
 * * -1 on error
 *
 * # Safety
 * `config_yaml` must be a valid null-terminated C string.
 */
long shoes_start(const char *config_yaml,
                 ProtectSocketCallback protect_callback,
                 ShoesTrafficCallback traffic_callback);

/**
 * Stop the shoes VPN service.
 *
 * # Arguments
 * * `handle` - Handle returned by shoes_start (currently unused, we use global state)
 */
void shoes_stop(long _handle);

/**
 * Check if the shoes service is running.
 *
 * # Returns
 * * true if running
 * * false if not running
 */
bool shoes_is_running(void);

/**
 * Get the shoes library version.
 *
 * # Returns
 * A static string containing the version. Do not free this pointer.
 */
const char *shoes_get_version(void);

/**
 * Set the log file path for file-based logging.
 *
 * # Arguments
 * * `path` - Absolute path to the log file
 *
 * # Returns
 * * 0 on success
 * * -1 on error
 *
 * # Safety
 * `path` must be a valid null-terminated C string.
 */
int shoes_set_log_file(const char *path);

/**
 * Change the log level of a running library.
 *
 * `shoes_init` reads the level once and ignores it on every later call, so
 * without this a support workflow of "turn on debug logging and reproduce"
 * means killing the app first. Takes effect immediately, for every subsequent
 * record.
 *
 * Note that release builds are compiled with `release_max_level_info`, so
 * "debug" and "trace" only differ from "info" in a build that keeps them.
 *
 * # Arguments
 * * `log_level` - "error", "warn", "info", "debug", "trace", or "off"
 *
 * # Returns
 * * 0 on success
 * * -1 if the level was not recognised
 *
 * # Safety
 * `log_level` must be a valid null-terminated C string.
 */
int shoes_set_log_level(const char *log_level);

/**
 * Tell the library the device's network changed.
 *
 * Call this from `NWPathMonitor`'s update handler. A UDP tunnel bound to an
 * address that no longer exists does not fail — it goes silent — so without
 * this the only recovery is a full stop and start, which tears down the TUN
 * interface and every connection through it. This rebinds the tunnel's socket
 * in place instead.
 *
 * Safe to call at any time, including when no tunnel is running. It does no
 * I/O on the calling thread.
 *
 * # Returns
 * The number of tunnel endpoints that were told to rebind.
 */
int shoes_network_changed(void);

/**
 * Get the last error message from the shoes service.
 *
 * Returns a null-terminated C string containing the error message,
 * or NULL if no error has occurred. The caller must free the returned
 * string using `shoes_free_string()`.
 *
 * Thread-safe. The returned string is a copy — safe to use after
 * subsequent shoes API calls.
 */
char *shoes_get_last_error(void);

/**
 * Free a string returned by `shoes_get_last_error()`.
 *
 * # Safety
 * `ptr` must be a pointer returned by `shoes_get_last_error()`, or NULL.
 */
void shoes_free_string(char *ptr);

#endif  /* SHOES_H */
